# Speed Constants
SPEED_HIGH = 2
SPEED_AVG = 1
SPEED_LOW = 0

# Offensive Constants
RATIO_OFFENSE_MIX = 2
RATIO_OFFENSE_SPA = 1
RATIO_OFFENSE_ATK = 0

# Offense/Defensive Constants
RATIO_OFFDEF_DEFENSIVE = 1
RATIO_OFFDEF_OFFENSIVE = 0
